### ISSUE TITLE
Feature idea: annotation to add setters to ValueObject that return new immutable object

### ISSUE THREAD

**Issue by JordanMartinez** [tvinke/bulletproof#4]
Just read your post on [Java Code Geeks](https://www.javacodegeeks.com/2017/09/make-groovy-objects-bullet-proof.html).

In my own code, I designed an immutable class not using the `@Immutable` annotation because I didn't think it allowed one to add setters to an immutable object:
````groovy
public class Person {
   String name;
   int age;

   // setter
   Person setName(String newName) {
      new Person(newName, age)
   }
````

Would you be interested in adding these "immutable setters" (not sure what else to call them) or some Groovy counterpart to `@ValueObject`? Or perhaps adding another annotation that combines `ValueObject` with this idea? I would roll my own annotation, but I haven't yet learned how to do that myself.

**Comment by tvinke** [comment]
Hi Jordan,

You know `Immutable` has [`copyWith`](http://docs.groovy-lang.org/2.4.7/html/gapi/groovy/transform/Immutable.html#copyWith) feature? This allows to create a _copy_ of your object, adjusting any property you specify, using a Map?

~~~groovy
 @groovy.transform.Immutable(copyWith = true)
 class Person {
     String name
     int age
 }

 def tim   = new Person( 'tim', 16)
 def alice = tim.copyWith( name:'alice' )

 assert tim.name == 'tim'
 assert alice.name == 'alice'
~~~


Since `@ValueObject` is a meta-annotation -- it also supports the the `copyWith` automatically.

~~~groovy
 @ValueObject(copyWith = true)
 class Person {
     String first, last
 }
~~~

Would `copyWith` already be the feature you're looking for?

**Comment by JordanMartinez** [comment]
Nope. I didn't know that existed. That's essentially what I want, but I wonder about its performance since it uses a map, not the actual type.

Thanks for the detailed explanation!
